describe("open account",()=>{
    it("creating an account",()=>{
        cy.visit("http://testingserver/domain/Online_Banking_System/")
        cy.title().should('eq','Online Banking System')
        cy.get('.online_services>ul>:nth-child(1)').click()
        cy.url().should('contain','Online_Banking_System/customer_reg_form.php')
        cy.get('[name="name"]').type("Rashi")
        cy.get('[name="gender"]')
        .select('Female')
        cy.get('[name="mobile"]').type(9543231563)
        cy.get('.container_regfrm_container_parent_child>form>:nth-child(4)').type("rashi@gmail.com")
        cy.get('[name="landline"]').type(334455)
        cy.get('[name="dob"]').type("1994-09-15")
        cy.get('[name="pan_no"]').type("AZDIJ3456H")
        cy.get('[name="citizenship"]').type("23456")
        cy.get('[name="homeaddrs"]').type("BTM")
        cy.get('[name="officeaddrs"]').type("banshankari")
        cy.get('[name="state"]')
        .select('Florida')
        cy.get('[name="city"]')
        .select('Houston')
        cy.get('[name="pin"]').type(540089)
        cy.get('[name="arealoc"]').type("park")
        cy.get('[name="nominee_name"]').type("dinesh")
        cy.get('[name="nominee_ac_no"]').type("2344678941")
        cy.get('[name="acctype"]')
        .select('Saving')
        cy.get('[name="submit"]').click()
        cy.title().should('include','Confirm')
        cy.get('[name="cnfrm-submit"]').click()
        cy.on('window.alert',(t)=>{
                  let msg=t.text()
                  cy.log(msg)
                  cy.log(typeof(msg))
                    let appno=msg.match(/\d+/)
                  cy.log(appno)
        })




    })
})